# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import typing
__all__ = [
    "Array",
]

@typing.final
class Array:
    def __new__(cls) -> Array: ...
    def close(self) -> None:
        r"""
        Closes the token, releasing all memory mapped files.
        
        A call to this method will release all memory mapped files associated with this token.
        All memory views obtained from this token will become invalid after this call, and accessing
        them will result in undefined behavior.
        This function is unsafe, call it carefully.
        
        After calling this method, any further calls to `memmap` will raise an error.
        This method is idempotent: calling it multiple times has no effect.
        """

