[package]
name = "zix"
version = "0.0.0"
edition = "2024"

[dependencies]
zix-macros = { path = "../zix-macros" }
ndarray = "0.17.0"
arrayvec = "0.7"
cfg-if = "1"
libc = "0.2"
memmap2 = "0.9"

# dtype scalar
half = { version = "2", default-features = false, optional = true }
num-complex = { version = "0.4", default-features = false, optional = true }

# codec
zstd = "0.13"

# schema
prost = "0.14"
zerocopy = { version = "0.8", features = ["derive", "std"] }


[build-dependencies]
prost-build = { version = "0.14", optional = true }


[features]
build-schema = ["prost-build"]
half = ["dep:half"]
num-complex = ["dep:num-complex"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[dev-dependencies]
paste = "1"
proptest = "1"
static_assertions = "1.1"
tempfile = "3"
