[package]
name = "jix-macros"
version = "0.0.4"
authors = ["Barak Ugav <barakugav@gmail.com>"]
edition = "2024"
rust-version = "1.89.0"
description = "Macros for the jix library"
readme = "README.md"
repository = "https://github.com/barakugav/jix"
license = "MIT OR Apache-2.0"
keywords = ["ndarray", "compression", "zstd"]
categories = ["data-structures", "compression", "science"]

[lib]
proc-macro = true

[dependencies]
syn = "3.0"
quote = "1.0"
proc-macro-crate = "3.5"


[dev-dependencies]
# `jix` is pulled in under a *different* name on purpose to test a few edge cases in the derive macro
jix_core = { package = "jix", path = "../jix" }
ndarray = ">=0.16,<0.18"
