[package]
name = "jix-macros"
version = "0.0.2"
authors = ["Barak Ugav <barakugav@gmail.com>"]
edition = "2024"
rust-version = "1.89.0"
description = "Macros for the jix library"
readme = "README.md"
repository = "https://github.com/barakugav/jix"
license = "Apache-2.0"
keywords = ["ndarray", "compression", "zstd"]
categories = ["data-structures", "compression", "science"]

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro-crate = "3.5"
