"""Generate the README's benchmark block from the same rows the report uses.

    python bench-report/build_readme_snippet.py --artifacts bench-artifacts

The README quotes a handful of numbers. Writing them by hand guarantees they drift from the report
the first time anything is re-run, so they are generated instead - from the same rows, with the
same baselines.
"""

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "jix-py" / "python"))

from benches import report_bars, report_spec  # noqa: E402

sys.path.insert(0, str(Path(__file__).parent))
from build_report import load_run  # noqa: E402

DOCS = "https://jix.readthedocs.io/en/stable/benchmarks/"


def fmt_time(seconds):
    for unit, div in (("s", 1.0), ("ms", 1e-3), ("us", 1e-6)):
        if seconds >= div:
            scaled = seconds / div
            return f"{scaled:.0f} {unit}" if scaled >= 10 else f"{scaled:.1f} {unit}"
    return f"{seconds * 1e9:.0f} ns"


def build(rows, platform, fast=False):
    """The README block. Every number comes from `rows`; only the prose is written here."""
    on = [row for row in rows if row["platform"] == platform]

    def one(section, case, library, baseline):
        value, ratio = report_bars.headline(on, section, case, library, baseline)
        return value, ratio

    # The aligned case: the read is exactly one block. Compared against `blosc2-chunked` rather
    # than `blosc2`, because that is Blosc2 given chunks matched to its blocks - its best showing
    # here, and the only comparison worth putting in a headline. Its default chunking is far worse,
    # which the report shows but the README should not lean on.
    read_case = report_spec.read_label(*report_spec.READ_CASES[1])
    read_jix, _ = one("read", read_case, "jix", "numpy")
    read_blosc2, _ = one("read", read_case, "blosc2-chunked", "numpy")

    chain_case = report_spec.chain_label(32)
    chain_jix, chain_speedup = one("chain", chain_case, "jix-plain", "numpy")
    chain_numpy, _ = one("chain", chain_case, "numpy", "numpy")

    mem_case = report_spec.chain_label(32)
    mem_jix, _ = one("chain_memory", mem_case, "jix", "numpy")
    mem_numpy, _ = one("chain_memory", mem_case, "numpy", "numpy")

    lines = []
    if fast:
        lines += [
            "<!-- GENERATED FROM A --fast RUN - low-fidelity numbers, do not publish. -->",
            "",
        ]
    lines += [
        "<!-- Generated by bench-report/build_readme_snippet.py - do not edit by hand. -->",
        "",
        "## Benchmarks",
        "",
        f"[![operation chains](bench-report/plots/chain.png)]({DOCS})",
        "",
        (
            f"Measured on {platform} against NumPy, Blosc2 and Zarr at matched codec settings "
            "(zstd level 3, byte-shuffle), single-threaded. Full results, methodology, and the "
            f"cases where jix comes out behind are in [the benchmark report]({DOCS})."
        ),
        "",
    ]
    if chain_speedup:
        lines.append(
            f"- **Operation chains: {chain_speedup:.1f}x faster than NumPy.** A 32-step elementwise "
            f"chain over two 104 MB arrays runs in {fmt_time(chain_jix)} against NumPy's "
            f"{fmt_time(chain_numpy)}. NumPy makes a full pass per step; jix makes one, keeping "
            "each region's intermediates in cache."
        )
    if read_jix and read_blosc2:
        lines.append(
            f"- **Random reads from a compressed array: {read_blosc2 / read_jix:.1f}x faster than "
            f"Blosc2** at the same compression ratio - {fmt_time(read_jix)} against "
            f"{fmt_time(read_blosc2)} for one block-sized region, with Blosc2 given chunks matched "
            "to its blocks."
        )
    if mem_jix and mem_numpy:
        lines.append(
            f"- **{mem_numpy / mem_jix:.1f}x less memory** for the same chain "
            f"({mem_jix / 1e6:.0f} MB against {mem_numpy / 1e6:.0f} MB), because the inputs stay "
            "compressed while they are operated on."
        )
    lines += [
        (
            "- **Uncompressed arrays are NumPy's speed.** Single elementwise operations on a plain "
            "in-memory buffer match NumPy, so there is no cost to entering a jix pipeline."
        ),
        "",
        (
            "jix is single-threaded, keeps no cache of decompressed blocks, and is slower than "
            "NumPy on `std` and on chains dominated by transcendental math. Those are in the "
            "report too."
        ),
        "",
    ]
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate the README benchmark block.")
    parser.add_argument("--artifacts", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path(__file__).parent / "readme-snippet.md")
    parser.add_argument("--platform", default=None, help="which runner to quote (default: the first published)")
    parser.add_argument("--fast", action="store_true", help="mark as low-fidelity when meta predates the flag")
    args = parser.parse_args(argv)

    rows, platforms, fast = [], [], False
    for meta_path in sorted(args.artifacts.glob("**/meta.json")):
        platform, run_rows, meta = load_run(meta_path.parent)
        rows += run_rows
        platforms.append(platform)
        fast = fast or bool(meta.get("fast"))
    ordered = [p for p in report_spec.PLATFORMS if p in platforms] or sorted(set(platforms))
    platform = args.platform or ordered[0]

    args.out.write_text(build(rows, platform, fast or args.fast))
    print(args.out)


if __name__ == "__main__":
    main()
