syntax = "proto3";

package zix.v1;

import "google/protobuf/empty.proto";

import "zix/v1/codec.proto";
import "zix/v1/dtype.proto";

message BlockTableHeader {
  zix.v1.Dtype dtype = 1;
  uint64 nitems = 2;
  uint64 block_size = 3;

  zix.v1.Codec codec = 4;
  repeated zix.v1.Filter filters = 5;

  oneof body_description {
    // The data is stored as two continuous sections: one for the compressed block data and one for the block offsets.
    // A table with { offset: i64, size: u64 } (C struct) rows exists immediately after this message,
    // with the first row describing the compressed block offsets section and the second row describing the block data
    // section.
    // The TOC is encoded in this way instead of repeated protobuf messages so it will have a fixed
    // size and we can override it in-place after writing the file body.
    google.protobuf.Empty continuous_v1 = 7;
  }
}
