// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ArrayHeader {
    #[prost(uint64, repeated, tag = "1")]
    pub shape: ::prost::alloc::vec::Vec<u64>,
    #[prost(uint64, repeated, tag = "2")]
    pub block_shape: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Codec {
    #[prost(oneof = "codec::Kind", tags = "1")]
    pub kind: ::core::option::Option<codec::Kind>,
}
/// Nested message and enum types in `Codec`.
pub mod codec {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Zstd(()),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Filter {
    #[prost(oneof = "filter::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<filter::Kind>,
}
/// Nested message and enum types in `Filter`.
pub mod filter {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        ByteShuffle(()),
        #[prost(message, tag = "2")]
        BitShuffle(()),
    }
}
/// Description of a type layout and inner fields
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dtype {
    #[prost(uint32, repeated, tag = "3")]
    pub shape: ::prost::alloc::vec::Vec<u32>,
    #[prost(uint32, tag = "4")]
    pub itemsize: u32,
    #[prost(uint32, tag = "5")]
    pub alignment: u32,
    #[prost(oneof = "dtype::Kind", tags = "1, 2")]
    pub kind: ::core::option::Option<dtype::Kind>,
}
/// Nested message and enum types in `Dtype`.
pub mod dtype {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "1")]
        Scalar(super::DtypeScalar),
        #[prost(message, tag = "2")]
        Struct(super::DtypeStruct),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DtypeScalar {
    #[prost(enumeration = "ScalarKind", tag = "1")]
    pub kind: i32,
    #[prost(enumeration = "Endianness", tag = "2")]
    pub endianness: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DtypeStruct {
    /// The fields of the struct dtype, sorted by their offsets in ascending order.
    #[prost(message, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<dtype_struct::Field>,
}
/// Nested message and enum types in `DtypeStruct`.
pub mod dtype_struct {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Field {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(uint32, tag = "2")]
        pub offset: u32,
        #[prost(message, optional, tag = "3")]
        pub dtype: ::core::option::Option<super::Dtype>,
    }
}
/// The kind of a scalar dtype
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ScalarKind {
    Unspecified = 0,
    I8 = 1,
    I16 = 2,
    I32 = 3,
    I64 = 4,
    U8 = 5,
    U16 = 6,
    U32 = 7,
    U64 = 8,
    F16 = 9,
    F32 = 10,
    F64 = 11,
    ComplexF32 = 12,
    ComplexF64 = 13,
    Bool = 14,
}
impl ScalarKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SCALAR_KIND_UNSPECIFIED",
            Self::I8 => "SCALAR_KIND_I8",
            Self::I16 => "SCALAR_KIND_I16",
            Self::I32 => "SCALAR_KIND_I32",
            Self::I64 => "SCALAR_KIND_I64",
            Self::U8 => "SCALAR_KIND_U8",
            Self::U16 => "SCALAR_KIND_U16",
            Self::U32 => "SCALAR_KIND_U32",
            Self::U64 => "SCALAR_KIND_U64",
            Self::F16 => "SCALAR_KIND_F16",
            Self::F32 => "SCALAR_KIND_F32",
            Self::F64 => "SCALAR_KIND_F64",
            Self::ComplexF32 => "SCALAR_KIND_COMPLEX_F32",
            Self::ComplexF64 => "SCALAR_KIND_COMPLEX_F64",
            Self::Bool => "SCALAR_KIND_BOOL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SCALAR_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "SCALAR_KIND_I8" => Some(Self::I8),
            "SCALAR_KIND_I16" => Some(Self::I16),
            "SCALAR_KIND_I32" => Some(Self::I32),
            "SCALAR_KIND_I64" => Some(Self::I64),
            "SCALAR_KIND_U8" => Some(Self::U8),
            "SCALAR_KIND_U16" => Some(Self::U16),
            "SCALAR_KIND_U32" => Some(Self::U32),
            "SCALAR_KIND_U64" => Some(Self::U64),
            "SCALAR_KIND_F16" => Some(Self::F16),
            "SCALAR_KIND_F32" => Some(Self::F32),
            "SCALAR_KIND_F64" => Some(Self::F64),
            "SCALAR_KIND_COMPLEX_F32" => Some(Self::ComplexF32),
            "SCALAR_KIND_COMPLEX_F64" => Some(Self::ComplexF64),
            "SCALAR_KIND_BOOL" => Some(Self::Bool),
            _ => None,
        }
    }
}
/// Endianness of a scalar
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Endianness {
    Unspecified = 0,
    Little = 1,
    Big = 2,
}
impl Endianness {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENDIANNESS_UNSPECIFIED",
            Self::Little => "ENDIANNESS_LITTLE",
            Self::Big => "ENDIANNESS_BIG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENDIANNESS_UNSPECIFIED" => Some(Self::Unspecified),
            "ENDIANNESS_LITTLE" => Some(Self::Little),
            "ENDIANNESS_BIG" => Some(Self::Big),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockTableHeader {
    #[prost(message, optional, tag = "1")]
    pub dtype: ::core::option::Option<Dtype>,
    #[prost(uint64, tag = "2")]
    pub nitems: u64,
    #[prost(uint64, tag = "3")]
    pub block_size: u64,
    #[prost(message, optional, tag = "4")]
    pub codec: ::core::option::Option<Codec>,
    #[prost(message, repeated, tag = "5")]
    pub filters: ::prost::alloc::vec::Vec<Filter>,
    #[prost(oneof = "block_table_header::BodyDescription", tags = "7")]
    pub body_description: ::core::option::Option<block_table_header::BodyDescription>,
}
/// Nested message and enum types in `BlockTableHeader`.
pub mod block_table_header {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum BodyDescription {
        /// The compressed block data is stored in a single continuous buffer, but the blocks within it
        /// may appear in any order ("continuous" refers to the data buffer, not to block ordering).
        /// The body is two continuous sections: one for the block locations and one for the compressed
        /// block data. The locations section holds (nblocks + 1) / 2 entries, each packing two blocks'
        /// (offset: \[u64; 2\], len: \[u32; 2\]) locations into one 24-byte entry (avoiding the padding a
        /// lone u64 + u32 would incur); block i occupies the `len` bytes of block_data starting at
        /// `offset`. Blocks need not be contiguous or in order.
        /// A table with { offset: i64, size: u64 } (C struct) rows exists immediately after this message,
        /// with the first row describing the block locations section and the second row describing the
        /// compressed block data section.
        /// The TOC is encoded in this way instead of repeated protobuf messages so it will have a fixed
        /// size and we can override it in-place after writing the file body.
        #[prost(message, tag = "7")]
        ContinuousV1(()),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileMetadata {
    #[prost(enumeration = "ArchiveType", tag = "1")]
    pub archive_type: i32,
    /// Library version encoded as a 64-bit unsigned integer.
    ///
    /// The u64 is encoded with the following bit field layout:
    ///    major          :  8 \[ 0.. 8\]
    ///    minor          :  8 \[ 8..16\]
    ///    patch          : 10 \[16..26\]
    ///    pre-release    :  6 \[26..32\]
    ///    build-metadata : 32 \[32..64\]
    /// Note that the major is the least significant byte, so comparing versions can NOT be done with
    /// a simple integer comparison.
    #[prost(uint64, tag = "2")]
    pub lib_version_semver: u64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ArchiveType {
    Unspecified = 0,
    BlockTable = 1,
    ArrayV1 = 2,
}
impl ArchiveType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARCHIVE_TYPE_UNSPECIFIED",
            Self::BlockTable => "ARCHIVE_TYPE_BLOCK_TABLE",
            Self::ArrayV1 => "ARCHIVE_TYPE_ARRAY_V1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARCHIVE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ARCHIVE_TYPE_BLOCK_TABLE" => Some(Self::BlockTable),
            "ARCHIVE_TYPE_ARRAY_V1" => Some(Self::ArrayV1),
            _ => None,
        }
    }
}
