use std::collections::HashMap;
use std::hash::{BuildHasherDefault, Hasher};
use std::num::NonZeroUsize;
use std::sync::atomic::{AtomicUsize, Ordering};

/// A process-wide unique identifier of the data of a storage that does non-constant work to
/// produce it (a compact array, an element-wise op or a reduction), the key of the
/// [`ReadContext`](crate::ReadContext) read cache.
///
/// Views of the same data (e.g. a borrowed or re-typed storage) share the id; new data gets a new
/// one. Ids are never reused, so a cached entry can never be mistaken for another storage's data.
///
/// `repr(transparent)` over a [`NonZeroUsize`] guarantees `Option<ArrayCacheId>` is a plain `usize`,
/// with `None` as zero.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(transparent)]
pub(crate) struct ArrayCacheId(NonZeroUsize);

static NEXT_CACHE_ID: AtomicUsize = AtomicUsize::new(1);

impl ArrayCacheId {
    #[inline(never)]
    pub(crate) fn new() -> Self {
        Self(NonZeroUsize::new(NEXT_CACHE_ID.fetch_add(1, Ordering::Relaxed)).unwrap())
    }
}

/// FxHash, the hasher of rustc: a multiply and rotate per word.
///
/// Ids are generated by the process rather than by users, so the [`ArrayCacheId`] hash map does not
/// need the default DoS-resistant, and slower, SipHash.
#[derive(Default)]
pub(crate) struct FxHasher(u64);
impl Hasher for FxHasher {
    #[inline]
    fn write(&mut self, bytes: &[u8]) {
        for chunk in bytes.chunks(8) {
            let mut word = [0u8; 8];
            word[..chunk.len()].copy_from_slice(chunk);
            self.write_u64(u64::from_le_bytes(word));
        }
    }

    #[inline]
    fn write_u64(&mut self, word: u64) {
        self.0 = (self.0.rotate_left(5) ^ word).wrapping_mul(0x51_7c_c1_b7_27_22_0a_95);
    }

    #[inline]
    fn write_usize(&mut self, word: usize) {
        self.write_u64(word as u64);
    }

    #[inline]
    fn finish(&self) -> u64 {
        self.0
    }
}
pub(crate) type FxBuildHasher = BuildHasherDefault<FxHasher>;

/// The number of entries an [`ArrayCacheIdMap`] stores inline.
const INLINE_LEN: usize = 2;

/// A map from [`ArrayCacheId`]s to `V`. Up to [`INLINE_LEN`] entries are stored inline, more in a hash
/// map (hashed with [`FxHasher`]).
#[derive(Clone, Debug)]
pub(crate) enum ArrayCacheIdMap<V> {
    /// Up to [`INLINE_LEN`] entries, in any slots: `keys[i]` and `values[i]` are both `Some` or both
    /// `None`. The keys are kept apart from the values so a lookup compares all of them at once.
    Inline {
        keys: [Option<ArrayCacheId>; INLINE_LEN],
        values: [Option<V>; INLINE_LEN],
    },
    /// More than [`INLINE_LEN`] entries.
    Heap(HashMap<ArrayCacheId, V, FxBuildHasher>),
}
impl<V> Default for ArrayCacheIdMap<V> {
    fn default() -> Self {
        Self::Inline {
            keys: [None; INLINE_LEN],
            values: [const { None }; INLINE_LEN],
        }
    }
}
impl<V> ArrayCacheIdMap<V> {
    #[inline]
    pub(crate) fn contains_key(&self, id: ArrayCacheId) -> bool {
        match self {
            // Compare all the keys without short-circuiting, so the comparisons are branchless (and
            // a single vector compare on targets with 64-bit lane compares).
            Self::Inline { keys, .. } => keys
                .iter()
                .fold(false, |found, &key| found | (key == Some(id))),
            Self::Heap(map) => map.contains_key(&id),
        }
    }

    #[inline]
    pub(crate) fn get(&self, id: ArrayCacheId) -> Option<&V> {
        match self {
            Self::Inline { keys, values } => {
                let i = keys.iter().position(|&key| key == Some(id))?;
                values[i].as_ref()
            }
            Self::Heap(map) => map.get(&id),
        }
    }

    /// Inserts `value` for `id`, returning the previous value of `id`, if any.
    pub(crate) fn insert(&mut self, id: ArrayCacheId, value: V) -> Option<V> {
        match self {
            Self::Inline { keys, values } => {
                if let Some(i) = keys.iter().position(|&key| key == Some(id)) {
                    return values[i].replace(value);
                }
                if let Some(i) = keys.iter().position(Option::is_none) {
                    keys[i] = Some(id);
                    values[i] = Some(value);
                    return None;
                }
                let mut map = HashMap::with_capacity_and_hasher(2 * INLINE_LEN, Default::default());
                for (key, value) in keys.iter().zip(values) {
                    map.insert(key.unwrap(), value.take().unwrap());
                }
                map.insert(id, value);
                *self = Self::Heap(map);
                None
            }
            Self::Heap(map) => map.insert(id, value),
        }
    }

    pub(crate) fn remove(&mut self, id: ArrayCacheId) -> Option<V> {
        match self {
            Self::Inline { keys, values } => {
                let i = keys.iter().position(|&key| key == Some(id))?;
                keys[i] = None;
                values[i].take()
            }
            Self::Heap(map) => map.remove(&id),
        }
    }

    pub(crate) fn keys(&self) -> impl Iterator<Item = ArrayCacheId> + '_ {
        let (inline, heap) = match self {
            Self::Inline { keys, .. } => (Some(keys.iter().flatten()), None),
            Self::Heap(map) => (None, Some(map.keys())),
        };
        inline
            .into_iter()
            .flatten()
            .chain(heap.into_iter().flatten())
            .copied()
    }

    /// Removes all the entries, passing their values to `f`. Clears the map in place, rather than
    /// moving it, as the inline variant can be large.
    pub(crate) fn clear_with(&mut self, f: impl FnMut(V)) {
        match self {
            Self::Inline { keys, values } => {
                *keys = [None; INLINE_LEN];
                values.iter_mut().filter_map(Option::take).for_each(f);
            }
            Self::Heap(map) => map.drain().map(|(_, value)| value).for_each(f),
        }
    }
}

/// A set of [`ArrayCacheId`]s: an [`ArrayCacheIdMap`] without values.
#[derive(Clone, Debug, Default)]
pub(crate) struct ArrayCacheIdSet(ArrayCacheIdMap<()>);
impl ArrayCacheIdSet {
    #[inline]
    pub(crate) fn contains(&self, id: ArrayCacheId) -> bool {
        self.0.contains_key(id)
    }

    /// Adds `id`, returning whether it was not in the set yet.
    pub(crate) fn insert(&mut self, id: ArrayCacheId) -> bool {
        self.0.insert(id, ()).is_none()
    }

    pub(crate) fn iter(&self) -> impl Iterator<Item = ArrayCacheId> + '_ {
        self.0.keys()
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::{ArrayCacheId, ArrayCacheIdMap, ArrayCacheIdSet, INLINE_LEN};

    #[test]
    fn option_array_id_is_a_usize() {
        assert_eq!(size_of::<Option<ArrayCacheId>>(), size_of::<usize>());
    }

    #[test]
    fn array_id_map_spills_to_the_heap() {
        let ids = (0..6).map(|_| ArrayCacheId::new()).collect::<Vec<_>>();
        let mut map = ArrayCacheIdMap::default();
        for (n, &id) in ids.iter().enumerate() {
            assert_eq!(map.insert(id, n), None);
            assert_eq!(map.insert(id, n * 10), Some(n));
            assert_eq!(
                matches!(map, ArrayCacheIdMap::Inline { .. }),
                n < INLINE_LEN
            );
            for (m, &id) in ids.iter().enumerate() {
                assert_eq!(map.contains_key(id), m <= n);
                assert_eq!(map.get(id), (m <= n).then_some(&(m * 10)));
            }
            let keys = map.keys().collect::<HashSet<_>>();
            assert_eq!(keys, ids[..=n].iter().copied().collect());
        }
        assert_eq!(map.remove(ids[2]), Some(20));
        assert_eq!(map.remove(ids[2]), None);
        let mut values = Vec::new();
        map.clear_with(|value| values.push(value));
        values.sort();
        assert_eq!(values, [0, 10, 30, 40, 50]);
        assert_eq!(map.keys().count(), 0);

        // Removing from the inline map frees a slot for the next insert.
        let mut map = ArrayCacheIdMap::default();
        for &id in &ids[..INLINE_LEN] {
            map.insert(id, ());
        }
        map.remove(ids[0]);
        map.insert(ids[4], ());
        assert!(matches!(map, ArrayCacheIdMap::Inline { .. }));
        assert!(map.contains_key(ids[4]) && !map.contains_key(ids[0]));
    }

    #[test]
    fn array_id_set() {
        let ids = (0..6).map(|_| ArrayCacheId::new()).collect::<Vec<_>>();
        let mut set = ArrayCacheIdSet::default();
        for (n, &id) in ids.iter().enumerate() {
            assert!(set.insert(id));
            assert!(!set.insert(id));
            assert!(ids
                .iter()
                .enumerate()
                .all(|(m, &id)| set.contains(id) == (m <= n)));
            let all = set.iter().collect::<HashSet<_>>();
            assert_eq!(all, ids[..=n].iter().copied().collect());
        }
    }
}
