use std::collections::HashMap;
use std::num::NonZeroUsize;
use std::sync::atomic::{AtomicUsize, Ordering};

use rustc_hash::FxBuildHasher;

/// A process-wide unique identifier of an array's data, used as a cache key.
///
/// Views of the same data (e.g. a borrowed or re-typed storage) share the id; new data gets a new
/// one. Ids are never reused, so a cached entry can never be mistaken for another array's data.
///
/// `repr(transparent)` over a [`NonZeroUsize`] guarantees `Option<ArrayId>` is a plain `usize`,
/// with `None` as zero.
#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
#[repr(transparent)]
pub(crate) struct ArrayId(NonZeroUsize);

static NEXT_ARRAY_ID: AtomicUsize = AtomicUsize::new(1);

impl ArrayId {
    pub(crate) fn new() -> Self {
        Self(NonZeroUsize::new(NEXT_ARRAY_ID.fetch_add(1, Ordering::Relaxed)).unwrap())
    }
}

/// A map from [`ArrayId`]s to `V`. Up to 4 entries are stored inline, more in a hash map.
///
/// Ids are generated by the process rather than by users, so the hash map uses the fast
/// non-cryptographic FxHash instead of the default DoS-resistant SipHash.
#[derive(Clone, Debug)]
pub(crate) enum ArrayIdMap<V> {
    /// Up to 4 entries, in any slots: `keys[i]` and `values[i]` are both `Some` or both `None`. The
    /// keys are kept apart from the values so a lookup compares all of them at once.
    Inline {
        keys: [Option<ArrayId>; 4],
        values: [Option<V>; 4],
    },
    /// More than 4 entries.
    Heap(HashMap<ArrayId, V, FxBuildHasher>),
}
impl<V> Default for ArrayIdMap<V> {
    fn default() -> Self {
        Self::Inline {
            keys: [None; 4],
            values: [const { None }; 4],
        }
    }
}
impl<V> ArrayIdMap<V> {
    #[inline]
    pub(crate) fn contains_key(&self, id: ArrayId) -> bool {
        match self {
            // Compare all the keys without short-circuiting, so the comparisons are branchless (and
            // a single vector compare on targets with 64-bit lane compares).
            Self::Inline { keys, .. } => keys
                .iter()
                .fold(false, |found, &key| found | (key == Some(id))),
            Self::Heap(map) => map.contains_key(&id),
        }
    }

    #[inline]
    pub(crate) fn get(&self, id: ArrayId) -> Option<&V> {
        match self {
            Self::Inline { keys, values } => {
                let i = keys.iter().position(|&key| key == Some(id))?;
                values[i].as_ref()
            }
            Self::Heap(map) => map.get(&id),
        }
    }

    /// Inserts `value` for `id`, returning the previous value of `id`, if any.
    pub(crate) fn insert(&mut self, id: ArrayId, value: V) -> Option<V> {
        match self {
            Self::Inline { keys, values } => {
                if let Some(i) = keys.iter().position(|&key| key == Some(id)) {
                    return values[i].replace(value);
                }
                if let Some(i) = keys.iter().position(Option::is_none) {
                    keys[i] = Some(id);
                    values[i] = Some(value);
                    return None;
                }
                let mut map = HashMap::with_capacity_and_hasher(8, FxBuildHasher);
                for (key, value) in keys.iter().zip(values) {
                    map.insert(key.unwrap(), value.take().unwrap());
                }
                map.insert(id, value);
                *self = Self::Heap(map);
                None
            }
            Self::Heap(map) => map.insert(id, value),
        }
    }

    pub(crate) fn remove(&mut self, id: ArrayId) -> Option<V> {
        match self {
            Self::Inline { keys, values } => {
                let i = keys.iter().position(|&key| key == Some(id))?;
                keys[i] = None;
                values[i].take()
            }
            Self::Heap(map) => map.remove(&id),
        }
    }

    pub(crate) fn keys(&self) -> impl Iterator<Item = ArrayId> + '_ {
        let (inline, heap) = match self {
            Self::Inline { keys, .. } => (Some(keys.iter().flatten()), None),
            Self::Heap(map) => (None, Some(map.keys())),
        };
        inline
            .into_iter()
            .flatten()
            .chain(heap.into_iter().flatten())
            .copied()
    }

    pub(crate) fn into_values(self) -> impl Iterator<Item = V> {
        let (inline, heap) = match self {
            Self::Inline { values, .. } => (Some(values.into_iter().flatten()), None),
            Self::Heap(map) => (None, Some(map.into_values())),
        };
        inline
            .into_iter()
            .flatten()
            .chain(heap.into_iter().flatten())
    }
}

/// A set of [`ArrayId`]s: an [`ArrayIdMap`] without values.
#[derive(Clone, Debug, Default)]
pub(crate) struct ArrayIdSet(ArrayIdMap<()>);
impl ArrayIdSet {
    #[inline]
    pub(crate) fn contains(&self, id: ArrayId) -> bool {
        self.0.contains_key(id)
    }

    /// Adds `id`, returning whether it was not in the set yet.
    pub(crate) fn insert(&mut self, id: ArrayId) -> bool {
        self.0.insert(id, ()).is_none()
    }

    pub(crate) fn iter(&self) -> impl Iterator<Item = ArrayId> + '_ {
        self.0.keys()
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashSet;

    use super::{ArrayId, ArrayIdMap, ArrayIdSet};

    #[test]
    fn option_array_id_is_a_usize() {
        assert_eq!(size_of::<Option<ArrayId>>(), size_of::<usize>());
    }

    #[test]
    fn array_id_map_spills_to_the_heap() {
        let ids = (0..6).map(|_| ArrayId::new()).collect::<Vec<_>>();
        let mut map = ArrayIdMap::default();
        for (n, &id) in ids.iter().enumerate() {
            assert_eq!(map.insert(id, n), None);
            assert_eq!(map.insert(id, n * 10), Some(n));
            assert_eq!(matches!(map, ArrayIdMap::Inline { .. }), n < 4);
            for (m, &id) in ids.iter().enumerate() {
                assert_eq!(map.contains_key(id), m <= n);
                assert_eq!(map.get(id), (m <= n).then_some(&(m * 10)));
            }
            let keys = map.keys().collect::<HashSet<_>>();
            assert_eq!(keys, ids[..=n].iter().copied().collect());
        }
        assert_eq!(map.remove(ids[2]), Some(20));
        assert_eq!(map.remove(ids[2]), None);
        let mut values = map.into_values().collect::<Vec<_>>();
        values.sort();
        assert_eq!(values, [0, 10, 30, 40, 50]);

        // Removing from the inline map frees a slot for the next insert.
        let mut map = ArrayIdMap::default();
        for &id in &ids[..4] {
            map.insert(id, ());
        }
        map.remove(ids[1]);
        map.insert(ids[4], ());
        assert!(matches!(map, ArrayIdMap::Inline { .. }));
        assert!(map.contains_key(ids[4]) && !map.contains_key(ids[1]));
    }

    #[test]
    fn array_id_set() {
        let ids = (0..6).map(|_| ArrayId::new()).collect::<Vec<_>>();
        let mut set = ArrayIdSet::default();
        for (n, &id) in ids.iter().enumerate() {
            assert!(set.insert(id));
            assert!(!set.insert(id));
            assert!(ids
                .iter()
                .enumerate()
                .all(|(m, &id)| set.contains(id) == (m <= n)));
            let all = set.iter().collect::<HashSet<_>>();
            assert_eq!(all, ids[..=n].iter().copied().collect());
        }
    }
}
