[package]
name = "jix"
version = "0.0.5"
authors = ["Barak Ugav <barakugav@gmail.com>"]
edition = "2024"
rust-version = "1.89.0"
description = "Multi-dimensional array library with block-compressed storage and lazy-evaluated operations"
readme = "README.md"
repository = "https://github.com/barakugav/jix"
license = "MIT OR Apache-2.0"
keywords = ["ndarray", "compression", "zstd"]
categories = ["data-structures", "compression", "science"]
include = [
    "Cargo.toml",
    "build.rs",
    "src/",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[dependencies]
jix-macros = { path = "../jix-macros", version = "=0.0.5" }
ndarray = ">=0.16,<0.18"
memmap2 = "0.9"
num-traits = "0.2" # TODO make it optional
zstd = { version = "0.13", default-features = false }
prost = "0.14"
half = { version = "2", default-features = false, features = [
    "num-traits",
], optional = true }
num-complex = { version = "0.4", default-features = false, optional = true }
multiversion = { version = "0.8.0", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"


[features]
default = ["multiversion"]

# Add the `half` crate for f16, and implement scalar kernels for it.
half = ["dep:half"]

# Add the `num-complex` crate for complex numbers, and implement scalar kernels for Complex<f32>
# and Complex<f64>.
num-complex = ["dep:num-complex"]


# Compile SIMD-specialized function clones dispatched at runtime by CPU features.
# By enabling this feature, you can get better performance on CPUs that support SIMD, specifically
# x86 system, with the cost of bigger binary size.
multiversion = ["dep:multiversion"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }
fastrand = "2"
paste = "1"
proptest = "1"
tempfile = "3"


[profile.bench]
inherits = "release"
debug = true

[[bench]]
name = "compact"
harness = false

[[bench]]
name = "compress_ratio"
harness = false

[[bench]]
name = "read"
harness = false

[[bench]]
name = "op1"
harness = false

[[bench]]
name = "reduction"
harness = false

[[bench]]
name = "nd_copy"
harness = false

[lib]
bench = false
