[package]
name = "jix"
version = "0.0.3"
authors = ["Barak Ugav <barakugav@gmail.com>"]
edition = "2024"
rust-version = "1.89.0"
description = "Multi-dimensional array library with block-compressed storage and lazy-evaluated operations"
readme = "README.md"
repository = "https://github.com/barakugav/jix"
license = "MIT OR Apache-2.0"
keywords = ["ndarray", "compression", "zstd"]
categories = ["data-structures", "compression", "science"]
include = [
    "Cargo.toml",
    "build.rs",
    "src/",
    "README.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[dependencies]
jix-macros = { path = "../jix-macros", version = "=0.0.3" }
ndarray = ">=0.16,<0.18"
memmap2 = "0.9"
num-traits = "0.2" # TODO make it optional
zstd = { version = "0.13", default-features = false }
prost = "0.14"
half = { version = "2", default-features = false, features = [
    "num-traits",
], optional = true }
num-complex = { version = "0.4", default-features = false, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"


[features]
default = []
half = ["dep:half"]
num-complex = ["dep:num-complex"]


[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]


[dev-dependencies]
paste = "1"
proptest = "1"
tempfile = "3"
