[project]
name = "jix"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["numpy~=2.0"]
dynamic = [
    "version",
    "readme",
    "description",
    "authors",
    "license",
    "keywords",
    "classifiers",
]


[project.urls]
documentation = "https://jix.readthedocs.io/en/latest/"
homepage = "https://github.com/barakugav/jix"
source = "https://github.com/barakugav/jix"
releasenotes = "https://github.com/barakugav/jix/releases"
issues = "https://github.com/barakugav/jix/issues"

[project.optional-dependencies]
tests = ["pytest"]

[tool.maturin]
python-source = "python"

[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"
